dkd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: dkd
    username: root
    password: ${common-pwd}
  redis:
    host: ${redis-host}
    port: 6379
    password: ${common-pwd}
  sms:
    key:
    secret:
    sign-name: 阿里云短信测试
    template-code: SMS_154950909
